function createfigure(X1, Y1, Y2)
%CREATEFIGURE(X1, Y1, Y2)
%  X1:  vector of semilogx x data
%  Y1:  vector of semilogx y data
%  Y2:  vector of semilogx y data

%  Auto-generated by MATLAB on 19-Nov-2022 21:01:11

% Create figure
figure;

% Create axes
axes1 = axes('Tag','phase','Position',[0.13 0.11 0.775 0.341162790697674]);
hold(axes1,'on');

% Create semilogx
semilogx(X1,Y1,'Tag','BodeLine','Color',[0 0 1],'ZDataSource','');

% Create ylabel
ylabel('Phase [deg]','Margin',2);

% Create xlabel
xlabel('Frequency [Hz]','Margin',2);

box(axes1,'on');
grid(axes1,'on');
hold(axes1,'off');
% Set the remaining axes properties
set(axes1,'ContextMenu','XMinorGrid','on','XMinorTick','on','XScale','log');
% Create axes
axes2 = axes('Tag','gain',...
    'Position',[0.13 0.583837209302326 0.775 0.341162790697675]);
hold(axes2,'on');

% Create semilogx
semilogx(X1,Y2,'DisplayName','1001','Tag','BodeLine','Color',[0 0 1],...
    'ZDataSource','');

% Create ylabel
ylabel('Gain [dB]','Margin',2);

% Create title
title('Pod EL stab PLANT','Margin',2);

box(axes2,'on');
grid(axes2,'on');
hold(axes2,'off');
% Set the remaining axes properties
set(axes2,'ContextMenu','XMinorGrid','on','XMinorTick','on','XScale','log');
% Create legend
legend1 = legend(axes2,'show');
set(legend1,'EdgeColor',[0 0 0]);

% uimenu currently does not support code generation, enter 'doc uimenu' for correct input syntax
% In order to generate code for uimenu, you may use GUIDE. Enter 'doc guide' for more information
% uimenu(...);

% uimenu currently does not support code generation, enter 'doc uimenu' for correct input syntax
% In order to generate code for uimenu, you may use GUIDE. Enter 'doc guide' for more information
% uimenu(...);

% uimenu currently does not support code generation, enter 'doc uimenu' for correct input syntax
% In order to generate code for uimenu, you may use GUIDE. Enter 'doc guide' for more information
% uimenu(...);

% uimenu currently does not support code generation, enter 'doc uimenu' for correct input syntax
% In order to generate code for uimenu, you may use GUIDE. Enter 'doc guide' for more information
% uimenu(...);

% uimenu currently does not support code generation, enter 'doc uimenu' for correct input syntax
% In order to generate code for uimenu, you may use GUIDE. Enter 'doc guide' for more information
% uimenu(...);

% uimenu currently does not support code generation, enter 'doc uimenu' for correct input syntax
% In order to generate code for uimenu, you may use GUIDE. Enter 'doc guide' for more information
% uimenu(...);

% uimenu currently does not support code generation, enter 'doc uimenu' for correct input syntax
% In order to generate code for uimenu, you may use GUIDE. Enter 'doc guide' for more information
% uimenu(...);

% uimenu currently does not support code generation, enter 'doc uimenu' for correct input syntax
% In order to generate code for uimenu, you may use GUIDE. Enter 'doc guide' for more information
% uimenu(...);

% uimenu currently does not support code generation, enter 'doc uimenu' for correct input syntax
% In order to generate code for uimenu, you may use GUIDE. Enter 'doc guide' for more information
% uimenu(...);

% uimenu currently does not support code generation, enter 'doc uimenu' for correct input syntax
% In order to generate code for uimenu, you may use GUIDE. Enter 'doc guide' for more information
% uimenu(...);

% uimenu currently does not support code generation, enter 'doc uimenu' for correct input syntax
% In order to generate code for uimenu, you may use GUIDE. Enter 'doc guide' for more information
% uimenu(...);

% uimenu currently does not support code generation, enter 'doc uimenu' for correct input syntax
% In order to generate code for uimenu, you may use GUIDE. Enter 'doc guide' for more information
% uimenu(...);

% uimenu currently does not support code generation, enter 'doc uimenu' for correct input syntax
% In order to generate code for uimenu, you may use GUIDE. Enter 'doc guide' for more information
% uimenu(...);

% uimenu currently does not support code generation, enter 'doc uimenu' for correct input syntax
% In order to generate code for uimenu, you may use GUIDE. Enter 'doc guide' for more information
% uimenu(...);

% uimenu currently does not support code generation, enter 'doc uimenu' for correct input syntax
% In order to generate code for uimenu, you may use GUIDE. Enter 'doc guide' for more information
% uimenu(...);

% uimenu currently does not support code generation, enter 'doc uimenu' for correct input syntax
% In order to generate code for uimenu, you may use GUIDE. Enter 'doc guide' for more information
% uimenu(...);

% uimenu currently does not support code generation, enter 'doc uimenu' for correct input syntax
% In order to generate code for uimenu, you may use GUIDE. Enter 'doc guide' for more information
% uimenu(...);

% uimenu currently does not support code generation, enter 'doc uimenu' for correct input syntax
% In order to generate code for uimenu, you may use GUIDE. Enter 'doc guide' for more information
% uimenu(...);

% uimenu currently does not support code generation, enter 'doc uimenu' for correct input syntax
% In order to generate code for uimenu, you may use GUIDE. Enter 'doc guide' for more information
% uimenu(...);

% uimenu currently does not support code generation, enter 'doc uimenu' for correct input syntax
% In order to generate code for uimenu, you may use GUIDE. Enter 'doc guide' for more information
% uimenu(...);

% uimenu currently does not support code generation, enter 'doc uimenu' for correct input syntax
% In order to generate code for uimenu, you may use GUIDE. Enter 'doc guide' for more information
% uimenu(...);

% uimenu currently does not support code generation, enter 'doc uimenu' for correct input syntax
% In order to generate code for uimenu, you may use GUIDE. Enter 'doc guide' for more information
% uimenu(...);

% uimenu currently does not support code generation, enter 'doc uimenu' for correct input syntax
% In order to generate code for uimenu, you may use GUIDE. Enter 'doc guide' for more information
% uimenu(...);

% uimenu currently does not support code generation, enter 'doc uimenu' for correct input syntax
% In order to generate code for uimenu, you may use GUIDE. Enter 'doc guide' for more information
% uimenu(...);

% uitoolbar currently does not support code generation, enter 'doc uitoolbar' for correct input syntax
% In order to generate code for uitoolbar, you may use GUIDE. Enter 'doc guide' for more information
% uitoolbar(...);

% uitoggletool currently does not support code generation, enter 'doc uitoggletool' for correct input syntax
% In order to generate code for uitoggletool, you may use GUIDE. Enter 'doc guide' for more information
% uitoggletool(...);

% uitoggletool currently does not support code generation, enter 'doc uitoggletool' for correct input syntax
% In order to generate code for uitoggletool, you may use GUIDE. Enter 'doc guide' for more information
% uitoggletool(...);

% uitoggletool currently does not support code generation, enter 'doc uitoggletool' for correct input syntax
% In order to generate code for uitoggletool, you may use GUIDE. Enter 'doc guide' for more information
% uitoggletool(...);

% uitoggletool currently does not support code generation, enter 'doc uitoggletool' for correct input syntax
% In order to generate code for uitoggletool, you may use GUIDE. Enter 'doc guide' for more information
% uitoggletool(...);

% uitoggletool currently does not support code generation, enter 'doc uitoggletool' for correct input syntax
% In order to generate code for uitoggletool, you may use GUIDE. Enter 'doc guide' for more information
% uitoggletool(...);

% uimenu currently does not support code generation, enter 'doc uimenu' for correct input syntax
% In order to generate code for uimenu, you may use GUIDE. Enter 'doc guide' for more information
% uimenu(...);

% uimenu currently does not support code generation, enter 'doc uimenu' for correct input syntax
% In order to generate code for uimenu, you may use GUIDE. Enter 'doc guide' for more information
% uimenu(...);

% uimenu currently does not support code generation, enter 'doc uimenu' for correct input syntax
% In order to generate code for uimenu, you may use GUIDE. Enter 'doc guide' for more information
% uimenu(...);

% uimenu currently does not support code generation, enter 'doc uimenu' for correct input syntax
% In order to generate code for uimenu, you may use GUIDE. Enter 'doc guide' for more information
% uimenu(...);

% uimenu currently does not support code generation, enter 'doc uimenu' for correct input syntax
% In order to generate code for uimenu, you may use GUIDE. Enter 'doc guide' for more information
% uimenu(...);

% uimenu currently does not support code generation, enter 'doc uimenu' for correct input syntax
% In order to generate code for uimenu, you may use GUIDE. Enter 'doc guide' for more information
% uimenu(...);

% uimenu currently does not support code generation, enter 'doc uimenu' for correct input syntax
% In order to generate code for uimenu, you may use GUIDE. Enter 'doc guide' for more information
% uimenu(...);

% uimenu currently does not support code generation, enter 'doc uimenu' for correct input syntax
% In order to generate code for uimenu, you may use GUIDE. Enter 'doc guide' for more information
% uimenu(...);

% uimenu currently does not support code generation, enter 'doc uimenu' for correct input syntax
% In order to generate code for uimenu, you may use GUIDE. Enter 'doc guide' for more information
% uimenu(...);

% uimenu currently does not support code generation, enter 'doc uimenu' for correct input syntax
% In order to generate code for uimenu, you may use GUIDE. Enter 'doc guide' for more information
% uimenu(...);

% uimenu currently does not support code generation, enter 'doc uimenu' for correct input syntax
% In order to generate code for uimenu, you may use GUIDE. Enter 'doc guide' for more information
% uimenu(...);

% uimenu currently does not support code generation, enter 'doc uimenu' for correct input syntax
% In order to generate code for uimenu, you may use GUIDE. Enter 'doc guide' for more information
% uimenu(...);

% uimenu currently does not support code generation, enter 'doc uimenu' for correct input syntax
% In order to generate code for uimenu, you may use GUIDE. Enter 'doc guide' for more information
% uimenu(...);

% uimenu currently does not support code generation, enter 'doc uimenu' for correct input syntax
% In order to generate code for uimenu, you may use GUIDE. Enter 'doc guide' for more information
% uimenu(...);

% uimenu currently does not support code generation, enter 'doc uimenu' for correct input syntax
% In order to generate code for uimenu, you may use GUIDE. Enter 'doc guide' for more information
% uimenu(...);

% uimenu currently does not support code generation, enter 'doc uimenu' for correct input syntax
% In order to generate code for uimenu, you may use GUIDE. Enter 'doc guide' for more information
% uimenu(...);

% uimenu currently does not support code generation, enter 'doc uimenu' for correct input syntax
% In order to generate code for uimenu, you may use GUIDE. Enter 'doc guide' for more information
% uimenu(...);

% uimenu currently does not support code generation, enter 'doc uimenu' for correct input syntax
% In order to generate code for uimenu, you may use GUIDE. Enter 'doc guide' for more information
% uimenu(...);

% uimenu currently does not support code generation, enter 'doc uimenu' for correct input syntax
% In order to generate code for uimenu, you may use GUIDE. Enter 'doc guide' for more information
% uimenu(...);

% uimenu currently does not support code generation, enter 'doc uimenu' for correct input syntax
% In order to generate code for uimenu, you may use GUIDE. Enter 'doc guide' for more information
% uimenu(...);

% uimenu currently does not support code generation, enter 'doc uimenu' for correct input syntax
% In order to generate code for uimenu, you may use GUIDE. Enter 'doc guide' for more information
% uimenu(...);

% uimenu currently does not support code generation, enter 'doc uimenu' for correct input syntax
% In order to generate code for uimenu, you may use GUIDE. Enter 'doc guide' for more information
% uimenu(...);

% uimenu currently does not support code generation, enter 'doc uimenu' for correct input syntax
% In order to generate code for uimenu, you may use GUIDE. Enter 'doc guide' for more information
% uimenu(...);

% uimenu currently does not support code generation, enter 'doc uimenu' for correct input syntax
% In order to generate code for uimenu, you may use GUIDE. Enter 'doc guide' for more information
% uimenu(...);

% uimenu currently does not support code generation, enter 'doc uimenu' for correct input syntax
% In order to generate code for uimenu, you may use GUIDE. Enter 'doc guide' for more information
% uimenu(...);

% uimenu currently does not support code generation, enter 'doc uimenu' for correct input syntax
% In order to generate code for uimenu, you may use GUIDE. Enter 'doc guide' for more information
% uimenu(...);

